apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "AI-extreme-edge-jetson-agx-xavier.fullname" . }}
  labels:
    {{- include "AI-extreme-edge-jetson-agx-xavier.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "AI-extreme-edge-jetson-agx-xavier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "AI-extreme-edge-jetson-agx-xavier.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "AI-extreme-edge-jetson-agx-xavier.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: x11-volume
        hostPath:
         path: /tmp/.X11-unix
         type: Directory
      - name: nvpmodel-mount
        hostPath:
         path: /usr/sbin/nvpmodel
      - name: nvpm-addition
        hostPath:
         path: /etc/nvpmodel.conf
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: DISPLAY
            value: :1
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
          - mountPath: /tmp/.X11-unix
            name: x11-volume
          - mountPath: /usr/sbin/nvpmodel
            name: nvpmodel-mount
          - mountPath: /etc/nvpmodel.conf
            name: nvpm-addition
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep"]
          args: ["infinity"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          #livenessProbe:
            #httpGet:
              #path: /
              #port: http
          #readinessProbe:
            #httpGet:
              #path: /
              #port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
