# Default values for human-presence.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#replicaCount: 1

apiVersion: v1
kind: Pod
metadata:
  name: human-presence-knf
  namespace: default
  labels:
    env: human-presence
spec:
  nodeName: compute
  containers:
  - name: human-presence
    image: pbasaras/iccs:nginx
    imagePullPolicy: Always
    ports:
    - containerPort: 80

#replicaCount: 1
